<#
.SYNOPSIS
    Starts the AD User Admin GUI application
.DESCRIPTION
    Loads config, and displays the main UI
#>
function Start-GUI {
    [CmdletBinding()]
    param()
    try {
        # Load config
        $configPath = Join-Path $PSScriptRoot "config\Config.psd1"

        if (-not (Test-Path $configPath)) {
            throw "Config file not found at: $configPath"
        }
        Write-Verbose "Loading config at $configPath"
        $config = Import-PowerShellDataFile -Path $configPath

        Write-Host "Active Directory User Administration Tool - GUI [v$($config.Application.Version)]" -ForegroundColor Yellow
        Write-Host "Config loaded"

        # Initialize AppState with config
        Write-Verbose "Initializing application state"
        Initialize-AppState -Config $config -RootPath $PSScriptRoot
        if(Test-AppStateInitialized) {
            Write-Host "Application state initialized"
        } else {
            throw "Application state failed to initialize"
        }

        # Get current domain from AppState
        $domain = Get-CurrentDomain
        
        # Load initial data files
        Write-Verbose "Loading data files"
        $dataFiles = Import-DataFiles
        Write-Host "Data files loaded"

        Write-Verbose "Initializing UI"
        # Initialize UI
        $iconPath = Join-Path $PSScriptRoot $config.UI.NavIcon
        $xamlPath = Join-Path $PSScriptRoot $config.UI.XamlFile
        $controls = Initialize-UI -XamlPath $xamlPath
        # Set controls in AppState
        Write-Verbose "Initializing controls"
        Set-AppControls -Controls $controls
        # Populate all fields/comboboxes
        Write-Verbose "Initializing data"
        Initialize-Data -Departments $dataFiles.Departments -Locations $dataFiles.Locations -IconPath $iconPath
        Write-Host "UI initialized"

        # Test AD connection
        try {
            $null = Get-ADDomain -Server $domain -ErrorAction Stop
            Write-Host "Active Directory connection to $domain established"
        }
        catch {
            throw "Active Directory connection failed"
        }

        # Establish sync server connection
        $sesync = $null
        try{
            $syncServer = (Get-ADConfig).SyncServers[0]
            $sesync = Connect-RemotePSSession $syncServer
            Write-Host "Session to sync server $syncServer established"
        }
        catch{
            throw "Connection to sync server failed"
        }
        
        # Establish Microsoft Graph connection
        try {
            $authConfig = Get-AuthConfig
            Connect-MicrosoftGraph -ClientId $authConfig.ClientId -Secret $authConfig.Secret -TenantId $authConfig.TenantId
        }
        catch {
            throw "Microsoft Graph connection failed: $($_.Exception)"
        }

        # Setup event handlers
        Register-EventHandlers -Session $sesync
        Write-Host "Event handlers registered"

        # Set admin name for greeting
        $adminName = Get-Admin
        $controls.dbAdminName.Text = $adminName

        # Show the window
        Write-Host "Launching application..." -ForegroundColor Cyan
        Write-Host $("=" * 100) -ForegroundColor Cyan
        Write-Log -Level "Info" -Message "User $adminName started a session."
        Show-UIWindow

    }
    catch {
        throw "Failed to start application: $($_.Exception.Message)"
    }
    finally {
        # Cleanup
        if ($null -ne $sesync) {
            $syncServer = (Get-ADConfig).SyncServers[0]
            Write-Host "Closing remote session to $syncServer" -ForegroundColor Yellow
            Remove-PSSession -Session $sesync -ErrorAction SilentlyContinue
        }
        
        Write-Host "Disconnecting from Microsoft Graph" -ForegroundColor Yellow
        Disconnect-MgGraph -ErrorAction SilentlyContinue > $null
        
        Write-Host "Cleanup complete" -ForegroundColor Cyan
        Write-Log -Level "Info" -Message "User $adminName closed their session."
    }
}

<#
.SYNOPSIS
    Registers all UI event handlers
.PARAMETER Session
    A session object generated by a server that will be in charge of running sync functions
#>
function Register-EventHandlers {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [object]$Session
    )

    $controls = Get-AppControls

    # ----------- Navigation events -----------
    $controls.btnDashboard.Add_Click({ 
            Switch-UIPage -ActiveButton (Get-AppControl 'btnDashboard')
            # Clear any generated or input passwords as the field should be empty when viewing a new user
            (Get-AppControl 'txtEditUserPassword').Text = ""
        })
    
    $controls.btnUsers.Add_Click({ 
            Search-ADUserAccounts -SearchText (Get-AppControl 'txtUserSearch').Text
            Switch-UIPage -ActiveButton (Get-AppControl 'btnUsers')
        })
    
    $controls.btnSync.Add_Click({ 
            Switch-UIPage -ActiveButton (Get-AppControl 'btnSync')
            (Get-AppControl 'txtEditUserPassword').Text = ""
        })
    
    $controls.btnUtilities.Add_Click({ 
            Switch-UIPage -ActiveButton (Get-AppControl 'btnUtilities')
            (Get-AppControl 'txtEditUserPassword').Text = ""
        })
    
    $controls.btnAdmin.Add_Click({ 
            Switch-UIPage -ActiveButton (Get-AppControl 'btnAdmin')
            (Get-AppControl 'txtEditUserPassword').Text = ""
        })
    
    # User management events
    $controls.btnUserSearch.Add_Click({ 
            Search-ADUserAccounts -SearchText (Get-AppControl 'txtUserSearch').Text
        })
    
    # Enter key triggers search
    $controls.txtUserSearch.Add_KeyDown({
            param($sender, $e)
            if ($e.Key -eq [System.Windows.Input.Key]::Return -or 
                $e.Key -eq [System.Windows.Input.Key]::Enter) {
                Search-ADUserAccounts -SearchText (Get-AppControl 'txtUserSearch').Text
            }
        })
    
    # ----------- Create user page -----------
    $controls.btnCreateUser.Add_Click({ 
            $dataFiles = Import-DataFiles
            Update-DataSources -DataFiles $dataFiles
            Switch-UIPage -ActiveButton (Get-AppControl 'btnCreateUser')
        })
    
    $controls.btnCreateToUserList.Add_Click({ 
            Switch-UIPage -ActiveButton (Get-AppControl 'btnCreateToUserList')
            Search-ADUserAccounts  
        })

    $controls.btnSubmitCreateUser.Add_Click({ 
            $dataFiles = Import-DataFiles
            if (New-ADUserAccount -DataFiles $dataFiles) {
                Switch-UIPage -ActiveButton (Get-AppControl 'btnCreateToUserList')
                Search-ADUserAccounts  
                Clear-UserVars 
            }
        })

    # ----------- Edit user page -----------
    $controls.btnEditUser.Add_Click({ 
        $selectedUser = (Get-AppControl 'dgUserList').SelectedItem
        if ($null -eq $selectedUser) {
            $appInfo = Get-AppInfo
            [void][System.Windows.MessageBox]::Show(
                "No user selected. Please select a user from the user list first.",
                $appInfo.Name,
                [System.Windows.MessageBoxButton]::OK,
                [System.Windows.MessageBoxImage]::Warning
            )
            return
        } else {
            $dataFiles = Import-DataFiles
            Update-DataSources -DataFiles $dataFiles
            Initialize-EditPage  
            Switch-UIPage -ActiveButton (Get-AppControl 'btnEditUser')
        }
        })
    
    $controls.btnSubmitEditUser.Add_Click({ 
            $dataFiles = Import-DataFiles
            if (Update-ADUserAccount -DataFiles $dataFiles -Validate $false) {
                Switch-UIPage -ActiveButton (Get-AppControl 'btnEditToUserList')
                Search-ADUserAccounts  
                Clear-UserVars 
            }
        })
    
    $controls.btnEditToUserList.Add_Click({ 
            Switch-UIPage -ActiveButton (Get-AppControl 'btnEditToUserList')
            (Get-AppControl 'txtEditUserPassword').Text = ""
            Search-ADUserAccounts  
        })

    $controls.btnEditRngPassword.Add_Click({ 
            $rngPassword = New-SecurePassword 
            (Get-AppControl 'txtEditUserPassword').Text = $rngPassword.Plain
        })

    # ----------- Util page -----------
    # ----------- Field Normalisation -----------
    $controls.btnUtilLoadFieldValues.Add_Click({
        return
    })

    # ----------- Sync page -----------
    $controls.btnDeltaSync.Add_Click({ 
            Start-DeltaSync -Session $Session 
    }.GetNewClosure())
}

<#
.SYNOPSIS
    Clears all fields set by the user
#>
function Clear-UserVars {
    (Get-AppControl 'txtCreateUserGivenName').Clear()
    (Get-AppControl 'txtCreateUserSurname').Clear()
    (Get-AppControl 'txtCreateUserDisplayName').Clear()
    (Get-AppControl 'txtCreateUserEmail').Clear()
    (Get-AppControl 'txtCreateUserSAMAccountName').Clear()
    (Get-AppControl 'txtCreateUserPassword').Clear()
    (Get-AppControl 'txtCreateUserTitle').Clear()
    (Get-AppControl 'cbCreateUserDepartment').SelectedItem = $null
    (Get-AppControl 'cbCreateUserLocation').SelectedItem = $null
    (Get-AppControl 'txtManagerSamName').Clear()
    (Get-AppControl 'txtBudgetCode').Clear()
    (Get-AppControl 'txtEmployeeID').Clear()
    (Get-AppControl 'txtADPID').Clear()
}

<#
.SYNOPSIS
    Loads data files from config
#>
function Import-DataFiles {
    [CmdletBinding()]
    param()
    
    $dataSourcesConfig = Get-DataSourcesConfig
    
    $data = @{}
    $domain = Get-CurrentDomain
    $rootPath = Get-AppRootPath
    
    $deptConfig = $dataSourcesConfig.Departments
    $locConfig = $dataSourcesConfig.Locations

    # Load departments
    $deptPath = Join-Path $rootPath "$($deptConfig.Path)\$domain\departments.csv"

    if (-not (Test-Path $deptPath)) {
        throw "Data file $deptPath not found"
    }
    
    $csvDepts = Import-Csv -Path $deptPath -ErrorAction Stop
    $data.Departments = $csvDepts.($deptConfig.Key)
    $data.DepCode = $csvDepts.($deptConfig.Code)
    Write-Verbose "Loaded $($data.Departments.Count) departments"

    $dfDepartments = New-Object System.Collections.Generic.List[PSObject]
        for ($i = 0; $i -lt $data.Departments.Count; $i++) {
            $Row = [PSCustomObject]@{
                Department = "$($data.Departments[$i])".Trim()
                DepCode    = "$($data.DepCode[$i])".Trim()
            }
            $dfDepartments.Add($Row)
        }
    
    # Load locations
    $locPath = Join-Path $rootPath "$($locConfig.Path)\$domain\officelocations.csv"
    
    if (-not (Test-Path $locPath)) {
        throw "Data file $locPath not found"
    }
    
    $csvLocs = Import-Csv -Path $locPath -ErrorAction Stop
    $data.Locations = $csvLocs.($locConfig.Key)
    $data.LocCode = $csvLocs.($locConfig.Code)
    $data.LocStreetAddress = $csvLocs.($locConfig.StreetAddress)
    $data.LocCity = $csvLocs.($locConfig.City)
    $data.LocState = $csvLocs.($locConfig.State)
    $data.LocCountry = $csvLocs.($locConfig.Country)
    $data.LocPostalCode = $csvLocs.($locConfig.PostalCode)
    $data.LocOfficePhone = $csvLocs.($locConfig.OfficePhone)
    Write-Verbose "Loaded $($data.Locations.Count) locations"
    
    $dfLocations = New-Object System.Collections.Generic.List[PSObject]
        for ($i = 0; $i -lt $data.Locations.Count; $i++) {
            $Row = [PSCustomObject]@{
                Location      = "$($data.Locations[$i])".Trim()
                OfficePhone   = "$($data.LocOfficePhone[$i])".Trim()
                StreetAddress = "$($data.LocStreetAddress[$i])".Trim()
                City          = "$($data.LocCity[$i])".Trim()
                State         = "$($data.LocState[$i])".Trim()
                Country       = "$($data.LocCountry[$i])".Trim()
                PostalCode    = "$($data.LocPostalCode[$i])".Trim()
            }
            $dfLocations.Add($Row)
        }

    return @{
       Locations = $dfLocations
       Departments = $dfDepartments
    }
}

function Connect-MicrosoftGraph {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string]$ClientId,

        [Parameter(Mandatory = $true)]
        [string]$Secret,
        
        [Parameter(Mandatory = $true)]
        [string]$TenantId
    )
    # Check that the Microsoft Graph module is installed and prompt to install it if it is not
    $mggraphmodule = Get-Module -ListAvailable Microsoft.Graph

    if ( $Null -eq $mggraphmodule.name ) {
        Write-Host "The MS Online module is not installed."
        Write-Host "Please run ""install-module -name Microsoft.Graph"" from an elevated PowerShell session to install the module."
        Return
    } else { Write-Host "The MS Graph module is installed." }

    # Connect to Entra using application authentication
    Write-Host "Checking connection to Entra..."
    Get-mgdomain -ErrorAction SilentlyContinue > $Null
    if($?) { Write-Host "You are already connected to Entra." }
    else {
        # Create a PSCredential Object Using the Client ID and Secure Client Secret
        $ClientSecretCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $ClientId, (ConvertTo-SecureString -AsPlainText $Secret -Force)
        Connect-Mggraph -TenantId $TenantId -ClientSecretCredential $ClientSecretCredential -NoWelcome
    }

    if($?) { Write-Host "You are now connected to Entra." }
    else {
        Write-Host "We were unable to connect you to Entra. Please check the error output to determine why you were unable to connect."
    }
}
