Import-Module "$PSScriptRoot\..\ADUserAdminGUI.Logging\Logging.psm1"
Import-Module "$PSScriptRoot\..\ADUserAdminGUI.AppState\AppState.psm1"

<#
.SYNOPSIS
    Connects to a remote PS Server and returns a session object
.PARAMETER RemotePSServer
    FQDN of the server we want to connect to
#>
function Connect-RemotePSSession {
	[CmdletBinding()]
	param (
        [Parameter(Mandatory = $true)]
		[string]$RemotePSServer	
	)
	process {
		$PSSession = New-PSSession -ComputerName $RemotePSServer										# Try to open a session with the specified server

		if ( $? ) { 																						#if successful, create the provided variable and save the session to that variable
            return $PSSession
		} else {
			if ( Test-Connection $RemotePSServer -count 1 -quiet ) { 										# if our first connection attempt fails, see if we can ping the server
				if ( $Null -eq $ADAdminCreds ) { $ADAdminCreds = Get-Credential -Credential "" }			# if we can ping the server, prompt for admin credentials and use those to try to connect
				$PSSession = New-PSSession -ComputerName $RemotePSServer -Credential $ADAdminCreds
				if ( $? ) {
                    return $PSSession
				} else {
                    throw
				}
			} else {
                throw
			}
		}
	}
}

<#
.SYNOPSIS
    Starts a delta sync on the specified domain
.PARAMETER Domain
    The domain to run a delta sync on
.PARAMETER Session
    A session object generated by a server that will be in charge of running sync functions
#>
function Start-DeltaSync{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [object]$Session
    )
    $appInfo = Get-AppInfo
    try{
        Write-Log -Caller "Start-DeltaSync" -Message "Initiated delta sync on domain $(Get-CurrentDomain)"
        Invoke-Command -Session $Session -ScriptBlock {
            Start-ADSyncSyncCycle -PolicyType Delta 
            }
        [System.Windows.MessageBox]::Show(
        "Delta sync initiated!",
        $appInfo.Name,
        [System.Windows.MessageBoxButton]::OK,
        [System.Windows.MessageBoxImage]::Information
    )
    }
    catch{
        Write-Log -Level "Error" -Message "Error starting sync: $($_.Exception.Message)"
        throw "Error starting sync: $($_.Exception)"
    }
}